# Generated by Django 3.2 on 2022-03-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_super_admin',
            new_name='is_admin',
        ),
    ]
