# Generated by Django 3.2 on 2022-03-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Errander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('lga', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('education_qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('internet_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('deadline_handling', models.TextField(blank=True, null=True)),
                ('project', models.TextField(blank=True, null=True)),
                ('expectation', models.TextField(blank=True, null=True)),
                ('relevant_information', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('familiar_location', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=operations.models.errander_image_location)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='errander', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=operations.models.customer_image_location)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
