# Generated by Django 3.2 on 2022-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errander',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
