# Generated by Django 3.2 on 2022-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_order_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='errander',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
