# Generated by Django 3.2 on 2022-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_delete_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateField(auto_now=True),
        ),
    ]
