# Generated by Django 3.2 on 2022-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_order_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_created',
        ),
    ]
